source 'https://rubygems.org'

gem 'async', '~> 2.0'
gem 'async-http', '~> 0.75'
gem 'pg', '~> 1.5'
gem 'protocol-rack', '~> 0.7'
gem 'roda', '~> 3.0'
gem 'sequel', '~> 5.0'
gem 'testcontainers', '~> 0.2'
